# This is a basic workflow to help you get started with Actions

name: basic_check.yml

# Controls when the workflow will run
on:
  # uncomment if we decide to run tests when merging to develeop branch
  # push:
    ## merges to develop branch
  #  branches: [develop]
  pull_request:
    # pull request to develop with a label
 #   types: [labeled]
    branches: [develop]

defaults:
  run:
    shell: bash

jobs:
  Run-task-workflow:
    if: ${{ github.actor == 'jardizzo' }}
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: run-task-workflow
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        run: |
          source /etc/profile.d/modules.sh
          source config/modules
          ./task.py
