# This is a basic workflow to help you get started with Actions

name: basic_check.yml

# Controls when the workflow will run
on:
  pull_request:
    branches: [develop]

defaults:
  run:
    shell: bash

jobs:
  Run-task-workflow:
    uses: CIWorkflows/Workflows/.github/workflows/swell-workflow02.yml@develop
          
